# Generated by Django 6.0.4 on 2026-04-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_profile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
